# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale Issue or Pull Request is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 1

staleLabel: stale

markComment: >
  This pull request has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

closeComment: >
  Closing due to 30 days of inactivity.
  See http://mooseframework.org/moose/framework_development/patch_to_code.html

# Limit to only `issues` or `pulls`
# only: issues
only: pulls
