# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   moose-dev/*
#
# As well as any directions pertaining to modifying those files.
{% set version = "2023.08.31" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: 0

requirements:
  build:
    - {{ moose_python }}
    - setuptools
  run:
    - {{ moose_test_tools }}
    - beautifulsoup4
    - livereload
    - pybtex
    - mock
    - pylatexenc
    - python
    - clang-tools

test:
  commands:
    - git clang-format -h
  imports:
    - bs4
    - livereload
    - pybtex
    - mock
    - pylatexenc

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-tools) acts as a top-level module designed to provide all
    dependencies required in order to run the TestHarness, clang-format, and create MOOSE
    Documentation.

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
    - loganharbour
