# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   moose-dev/*
#
# As well as any directions pertaining to modifying those files.
{% set version = "2023.10.19" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: 0

requirements:
  build:
    - {{ moose_python }}
    - setuptools
  run:
    - beautifulsoup4
    - {{ clang_format }}
    - clang-tools
    - deepdiff
    - gitpython
    - graphviz
    - jinja2
    - livereload
    - lxml
    - mako
    - matplotlib-base
    - mock
    - numpy
    - packaging
    - pandas
    - psycopg2
    - pybtex
    - pycobertura
    - pyflakes
    - pylatexenc
    - pylint
    - python
    - pyyaml
    - scikit-image
    - setuptools
    - sympy
    - tabulate
    - xmltodict
    - yaml

test:
  commands:
    - clang-format --version
    - dot -V
    - pg_config --help
  imports:
    - bs4
    - deepdiff
    - git
    - jinja2
    - livereload
    - lxml
    - matplotlib
    - mock
    - numpy
    - pandas
    - psycopg2
    - pybtex
    - pycobertura
    - pyflakes
    - pylatexenc
    - pylint
    - skimage
    - sympy
    - tabulate
    - xmltodict
    - yaml

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-tools) acts as a top-level module designed to provide all
    dependencies required in order to run the TestHarness, clang-format, and create MOOSE
    Documentation.

extra:
  recipe-maintainers:
    - milljm
    - cticenhour
    - loganharbour
