{% set build = 0 %}
{% set version = "2022.07.18" %}

package:
  name: moose-peacock
  version: {{ version }}

source:
  path: ../peacock

build:
  number: {{ build }}

requirements:
  build:
    - {{ moose_python }}
    - openssl
    - setuptools
  run:
    - pyqt
    - vtk
    - matplotlib
    - pandas
    - python
    - openssl
    - setuptools

test:
  imports:
    - PyQt5
    - matplotlib
    - pandas
    - vtk

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: >
    This superficial module (moose-tools) acts as a top-level module designed to provide all
    dependencies required in order to run Peacock and MOOSE Documentation.

extra:
  recipe-maintainers:
    - milljm
