# Making a Change to this package?
# REMEMBER TO UPDATE the .yaml files for the following packages:
#   libmesh/*
#
# As well as any directions pertaining to modifying those files.
# ALSO: Follow the directions in scripts/tests/versioner_hashes.yaml
{% set build = 10 %}
{% set version = "3.16.6" %}

# permanent
{% set strbuild = "build_" + build|string %}

package:
  name: moose-petsc
  version: {{ version }}

source:
  - path: ../../petsc
  - path: ../../scripts/configure_petsc.sh
  - patches:
      - no-cppflags-in-pkgconfig-cflags.patch

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true  # [win]
  script_env:
    - MOOSE_JOBS
  run_exports:
    - {{ pin_subpackage('moose-petsc', max_pin='x.x')}}

requirements:
  build:
    - {{ moose_mpich }}
    - pkg-config
  host:
    - {{ moose_mpich }}
  run:
    - {{ moose_mpich }}

test:
  requires:
    - pkg-config
    - {{ moose_mpich }}

  files:
    - tests/ex1.c
    - tests/ex1f.F90
    - tests/makefile
  commands:
    - pkg-config --validate PETSc
    - pkg-config --cflags PETSc
    - pkg-config --libs PETSc

about:
  home: https://petsc.org
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - milljm
